### ISSUE TITLE
How to setup?

### ISSUE THREAD

**Issue by Acanis87** [Hypfer/hass-scene_presets#13]
Hey, I found your custom integration, but Iam not sure how to set it up. I did install it as a custom repository in HACS and downloaded it. It didnt appear in my sidebar (after restarting and clearing the cache).

The readme says "After the install via HACS, you must then set it up via a config flow that does nothing." => I have no clue, what that means... I did google "config flow" in context of Home Assisstant, but I really dont know what to do...^^

Could you add some extra explanation, please? 

Thanks!

**Comment by Hypfer** [comment]
I've just updated the readme. That should hopefully be sufficient to get you up and running
