### ISSUE TITLE
Dim-only bulbs

### ISSUE THREAD

**Issue by ruud-coder** [Hypfer/hass-scene_presets#18]
### What is happening?

Hi, i have a few Hue white ambiance lights and a zigbee dimmer switch (Ecodim) that controls regular lights. 

With the Hue app/bridge, setting a scene would also adjust the brightness for the dimmer, the scene presets plug-in doesn’t do anything when these bulbs are selected when setting a scene. Is it possible to change this?

### What should be happening?

When I set a scene to “rest” or “relax”, the contrast of the selected dimmer switch should be updated to match te scene. This would allow me to set a scene for the whole room.

### Reflection 1

Balanced View

### Is this issue tracker the right place for this topic?

I can manually change the brightness of the dimmer with home assistant.

### Please enter the scene_preset version you're using

1.2.2

### Please enter the Home Assistant version you're using

2024.2.2

### Details about your setup

ECO-DIM.05 connected to Zigbee controller SLZB-06, Zigbee2MQTT. 

### Reflection 2

HA and Zigbee2MQTT both running in Docker on a Synology NAS

### Time and Effort

- [X] Yes, I did my homework.
- [X] I understand that my issue will be deleted with no further comment if I did not do my homework.

**Comment by Hypfer** [comment]
I initially decided against supporting that, because I did not think that it would be of much use, however since it is useful to you, it is now possible with version 1.2.3

**Comment by ruud-coder** [comment]
That’s a lightning fast fix :-)
Thanks a lot!
