### ISSUE TITLE
Support for supported_color_mode hs

### ISSUE THREAD

**Issue by cloudhaus** [Hypfer/hass-scene_presets#3]
I have a mixture of hue bulbs and LIFX bulbs. The integration works against the hue bulbs as expected. Thank you!

The LIFX bulbs do not change colour. I found in Developer tools for the LIFX bulb that `supported_color_modes: color_temp, hs`

I changed the line in `presets.py` that checks for `xy` to `hs` and restarted Home Assistant. The integration successfully works against the LIFX bulbs.

Can you consider making this change in the source code? By supporting `xy` (hue) and `hs` LIFX we can support more bulbs.

```
        if "xy" in hass_state.attributes.get("supported_color_modes", ""):
```

Thanks  

```
min_color_temp_kelvin: 1500
max_color_temp_kelvin: 9000
min_mireds: 111
max_mireds: 666
effect_list: effect_colorloop, effect_pulse, effect_stop
supported_color_modes: color_temp, hs
color_mode: hs
brightness: 255
hs_color: 277.239, 34.118
rgb_color: 221, 168, 255
xy_color: 0.315, 0.231
friendly_name: Work Desk A19 1
supported_features: 36
```

**Comment by marcelveldt** [comment]
It should preferrably just check for all color modes then, which is xy, rgb and hs

**Comment by Hypfer** [comment]
This did work before. Then it didn't anymore. Now it does again
b5a00007
