### ISSUE TITLE
Custom brightness for different lights

### ISSUE THREAD

**Issue by HenrikHills** [Hypfer/hass-scene_presets#32]
### What is happening?

When applying a scene with (and without) a custom brightness all of the lights in the selected ‘group’ is set to the specified brightness(custom or scene-selected), I would like to change the brightness of some accent-lights without them defaulting to the default brightness of the scene…

is it doable to have different brightness for the lights in a scene (or if the scenes only changes the color of the bulbs, and doesn’t touch the brightness-part?)

I knowni can apply 2-3 instances of the same scene with different brightness but that is getting a negative WAF :(

### What should be happening?

Brightness for lights in a active scene should not be changed by integration and stay on brightness from before scene was applied

### Reflection 1

Balanced View

### Is this issue tracker the right place for this topic?

The scene changes brightness by either default from scene or custom set brightness 

### Please enter the scene_preset version you're using

Any

### Please enter the Home Assistant version you're using

2024.11.3

### Details about your setup

Z2M, Hue, IKEA, Namron

### Reflection 2

No

### Time and Effort

- [X] Yes, I did my homework.
- [X] I understand that my issue will be deleted with no further comment if I did not do my homework.

**Comment by Hypfer** [comment]
Out of scope for this integration, however https://github.com/fredck/lightener might help you with that problem

**Comment by ironcrafter54** [comment]
Could this be reconsidered but rather than the complexities mentioned in the original post the lights rather remain the brightness that they were set to before the scene is activated? Great integration btw, super useful.
