### ISSUE TITLE
Halloween Scenes

### ISSUE THREAD

**Issue by bmolitor** [Hypfer/hass-scene_presets#4]
Would you consider adding the currently available Halloween scenes from the Hue app?

Unfortunately, as I don't own enough RGB lights, I can't reliably get all colors to extract their values; extracting them from palette sreenshots seems to be a valid substitute, though. Do you need them in x,y, or would rgb values work as well?

**Comment by Hypfer** [comment]
Done, have fun :)

https://github.com/Hypfer/hass-scene_presets/commit/067c7814fd7f81789f5b8537fef4cf3958491046

**Comment by bmolitor** [comment]
Nice! Thanks! :-D
