### ISSUE TITLE
RGBW support

### ISSUE THREAD

**Issue by mckochan** [Hypfer/hass-scene_presets#8]
I have some bulbs that show up as RGBW:

```
supported_color_modes:
  - color_temp
  - rgbw
color_mode: rgbw
brightness: 255
color_temp_kelvin: null
color_temp: null
hs_color:
  - 193.176
  - 100
rgb_color:
  - 0
  - 199
  - 255
xy_color:
  - 0.147
  - 0.252
rgbw_color:
  - 0
  - 199
  - 255
  - 0
supported_features: 4
```
When applying presets to these bulbs, the colors are very washed out as it is applying 100% white as well as color. If I click the bulb in UI, I have to manually lower the "White Brightness" to 0 to get the proper color. 

Let me know if you need any other info, I appreciate your work, thank you!

**Comment by Hypfer** [comment]
This integration can't fix those RGBW lights of undisclosed type.
All it does is wrap `light.turn_on` with some comfort features.

Whatever issue it is you might be seeing is entirely unrelated to this
